cat <<EOF > cd-repo/argo/bankapp-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/cd-repo
    targetRevision: HEAD
    path: charts/bankapp
    helm:
      valueFiles:
        - ../../values/dev/bankapp-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bankapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOF
